# Generated by Django 4.0 on 2022-07-16 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='product_name',
            new_name='product_id',
        ),
    ]
